version: 0.2
phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - npm run build
      - npm run deploy
artifacts:
  files:
    - template.yaml
    - packaged.yaml
    - .aws-sam/**/*
